package com.ctsec.dao.jf;

import com.ctsec.model.jf.DimBranch;
import com.ctsec.vo.Branch;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Deprecated
public interface DimBranchMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uf20_dim_branch
     *
     * @mbggenerated Thu Nov 09 10:57:41 CST 2017
     */
    DimBranch selectByPrimaryKey(@Param("id") Integer id);

    List<Branch> selectBranch();

}