package com.ctsec.dao.jf;

import com.ctsec.model.jf.DimDate;
import com.ctsec.vo.TradingDay;
import org.apache.ibatis.annotations.Param;

public interface DimDateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uf20_dim_date
     *
     * @mbggenerated Thu Jan 11 16:35:07 CST 2018
     */
    DimDate selectByPrimaryKey(Integer day_id);

    TradingDay selectTradingDay(@Param("dayId") Integer dayId);
}