package com.ctsec.dao.jf;

import com.ctsec.model.jf.KapCubeInfo;
import com.ctsec.vo.CubeInfo;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface KapCubeInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kap_cube_info
     *
     * @mbggenerated Mon Dec 18 19:30:19 CST 2017
     */
    KapCubeInfo selectByPrimaryKey(@Param("init_date") Integer init_date, @Param("cube_name") String cube_name);

    List<CubeInfo> selectAll();

    List<CubeInfo> selectOne(@Param("cubeName") String cubeName);
}