package com.ctsec.dao.jf;

import com.ctsec.model.jf.KLine;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Deprecated
public interface KLineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jy_k_day
     *
     * @mbggenerated Thu Nov 02 14:36:21 CST 2017
     */
    KLine selectByPrimaryKey(@Param("init_date") Integer init_date, @Param("secu_code") String secu_code);

    List<KLine> selectDayKLine(@Param("secuCode") String secuCode, @Param("fromDate") Integer fromDate);

    List<KLine> selectMonthKLine(@Param("secuCode") String secuCode, @Param("fromDate") Integer fromDate);

    List<KLine> selectYearKLine(@Param("secuCode") String secuCode);
}