package com.ctsec.dao.jf;

import com.ctsec.model.jf.MenuAccess;
import com.ctsec.vo.MenuAccessInfo;
import org.apache.ibatis.annotations.Param;

import java.util.List;

/**
 * 权限管理-菜单访问权限信息数据访问接口层
 * 通过Mysql对菜单访问权限信息查询
 *
 * Created by luchisheng on 2017/12/05.
 */

public interface MenuAccessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jf_menu
     *
     * @mbggenerated Tue Dec 05 09:49:13 CST 2017
     */
    MenuAccess selectByPrimaryKey(@Param("id") Integer id);

    List<MenuAccessInfo> selectByRoleId(@Param("roleIds") String roleIds);

}