package com.ctsec.dao.jf;

import com.ctsec.model.jf.RelationGroup;
import com.ctsec.vo.Relation;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface RelationGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_group
     *
     * @mbggenerated Fri Dec 15 13:24:50 CST 2017
     */
    RelationGroup selectByPrimaryKey(@Param("id") Long id);

    Integer selectOneCount(@Param("groupName") String groupName);

    List<String> selectMatch(@Param("groupName") String groupName);

    RelationGroup selectOne(@Param("groupName") String groupName);

    List<RelationGroup> selectAll();

    List<RelationGroup> selectAll2();

    List<Relation> selectGroupAndItem();

    void insertOne(@Param("group") RelationGroup group);

    void deleteOne(@Param("id") Long id);

    void deleteOneByName(@Param("groupName") String groupName);

}