package com.ctsec.dao.jf;

import com.ctsec.model.jf.RelationItem;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface RelationItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_item
     *
     * @mbggenerated Fri Jan 05 17:21:49 CST 2018
     */
    RelationItem selectByPrimaryKey(@Param("id") Long id);

    List<RelationItem> selectByGroupId(@Param("groupId") Long groupId);

    List<RelationItem> selectByCode(@Param("code") String code);

    Integer selectOneCount(@Param("relationItem") RelationItem relationItem);

    Integer selectOneCountById(@Param("relationItem") RelationItem relationItem);

    void insertBatch(@Param("relationItemList") List<RelationItem> relationItemList);

    void insertOne(@Param("relationItem") RelationItem relationItem);

    void updateOne(@Param("relationItem") RelationItem relationItem);

    void deleteOne(@Param("id") Long id);

    void deleteAll(@Param("groupId") Long groupId);

    void deleteAllByGroupName(@Param("groupName") String groupName);
}