package com.ctsec.dao.jf;

import com.ctsec.model.jf.ReportIndex;
import org.apache.ibatis.annotations.Param;

import java.util.List;

/**
 * 经营报表指标筛选信息数据访问接口层
 * 通过Mysql对经营报表指标筛选信息查询
 *
 * Created by luchisheng on 2017/11/14.
 */

public interface ReportIndexMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_index
     *
     * @mbggenerated Tue Nov 14 09:23:45 CST 2017
     */
    ReportIndex selectByPrimaryKey(@Param("id") Long id);

    /**
     * 查询指标筛选信息
     * @param reportId
     * @return
     */
    List<ReportIndex> selectIndex(@Param("reportId") String reportId);
}