package com.ctsec.dao.jf;

import com.ctsec.model.jf.TradeStatisticsSz;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TradeStatisticsSzMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_statistics_sz
     *
     * @mbggenerated Tue Dec 12 16:29:18 CST 2017
     */
    TradeStatisticsSz selectByPrimaryKey(@Param("month_id") Integer month_id, @Param("secu_id") Integer secu_id);

    void batchSaveOrUpdate(@Param("szTrades") List<TradeStatisticsSz> data);

    void deleteByMonth(@Param("month") Integer month);
}