package com.ctsec.model.jf;

public class DimBranch {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uf20_dim_branch.id
     *
     * @mbggenerated Thu Nov 09 10:57:41 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uf20_dim_branch.p_id
     *
     * @mbggenerated Thu Nov 09 10:57:41 CST 2017
     */
    private Integer p_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uf20_dim_branch.name
     *
     * @mbggenerated Thu Nov 09 10:57:41 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uf20_dim_branch.lat
     *
     * @mbggenerated Thu Nov 09 10:57:41 CST 2017
     */
    private Double lat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uf20_dim_branch.lng
     *
     * @mbggenerated Thu Nov 09 10:57:41 CST 2017
     */
    private Double lng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uf20_dim_branch.province
     *
     * @mbggenerated Thu Nov 09 10:57:41 CST 2017
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uf20_dim_branch.city
     *
     * @mbggenerated Thu Nov 09 10:57:41 CST 2017
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uf20_dim_branch.category
     *
     * @mbggenerated Thu Nov 09 10:57:41 CST 2017
     */
    private String category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uf20_dim_branch.merge_no
     *
     * @mbggenerated Thu Nov 09 10:57:41 CST 2017
     */
    private String merge_no;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uf20_dim_branch.update_time
     *
     * @mbggenerated Thu Nov 09 10:57:41 CST 2017
     */
    private Integer update_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uf20_dim_branch.remark
     *
     * @mbggenerated Thu Nov 09 10:57:41 CST 2017
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uf20_dim_branch
     *
     * @mbggenerated Thu Nov 09 10:57:41 CST 2017
     */
    public DimBranch(Integer id, Integer p_id, String name, Double lat, Double lng, String province, String city, String category, String merge_no, Integer update_time, String remark) {
        this.id = id;
        this.p_id = p_id;
        this.name = name;
        this.lat = lat;
        this.lng = lng;
        this.province = province;
        this.city = city;
        this.category = category;
        this.merge_no = merge_no;
        this.update_time = update_time;
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uf20_dim_branch
     *
     * @mbggenerated Thu Nov 09 10:57:41 CST 2017
     */
    public DimBranch() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uf20_dim_branch.id
     *
     * @return the value of uf20_dim_branch.id
     *
     * @mbggenerated Thu Nov 09 10:57:41 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uf20_dim_branch.id
     *
     * @param id the value for uf20_dim_branch.id
     *
     * @mbggenerated Thu Nov 09 10:57:41 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uf20_dim_branch.p_id
     *
     * @return the value of uf20_dim_branch.p_id
     *
     * @mbggenerated Thu Nov 09 10:57:41 CST 2017
     */
    public Integer getP_id() {
        return p_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uf20_dim_branch.p_id
     *
     * @param p_id the value for uf20_dim_branch.p_id
     *
     * @mbggenerated Thu Nov 09 10:57:41 CST 2017
     */
    public void setP_id(Integer p_id) {
        this.p_id = p_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uf20_dim_branch.name
     *
     * @return the value of uf20_dim_branch.name
     *
     * @mbggenerated Thu Nov 09 10:57:41 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uf20_dim_branch.name
     *
     * @param name the value for uf20_dim_branch.name
     *
     * @mbggenerated Thu Nov 09 10:57:41 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uf20_dim_branch.lat
     *
     * @return the value of uf20_dim_branch.lat
     *
     * @mbggenerated Thu Nov 09 10:57:41 CST 2017
     */
    public Double getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uf20_dim_branch.lat
     *
     * @param lat the value for uf20_dim_branch.lat
     *
     * @mbggenerated Thu Nov 09 10:57:41 CST 2017
     */
    public void setLat(Double lat) {
        this.lat = lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uf20_dim_branch.lng
     *
     * @return the value of uf20_dim_branch.lng
     *
     * @mbggenerated Thu Nov 09 10:57:41 CST 2017
     */
    public Double getLng() {
        return lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uf20_dim_branch.lng
     *
     * @param lng the value for uf20_dim_branch.lng
     *
     * @mbggenerated Thu Nov 09 10:57:41 CST 2017
     */
    public void setLng(Double lng) {
        this.lng = lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uf20_dim_branch.province
     *
     * @return the value of uf20_dim_branch.province
     *
     * @mbggenerated Thu Nov 09 10:57:41 CST 2017
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uf20_dim_branch.province
     *
     * @param province the value for uf20_dim_branch.province
     *
     * @mbggenerated Thu Nov 09 10:57:41 CST 2017
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uf20_dim_branch.city
     *
     * @return the value of uf20_dim_branch.city
     *
     * @mbggenerated Thu Nov 09 10:57:41 CST 2017
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uf20_dim_branch.city
     *
     * @param city the value for uf20_dim_branch.city
     *
     * @mbggenerated Thu Nov 09 10:57:41 CST 2017
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uf20_dim_branch.category
     *
     * @return the value of uf20_dim_branch.category
     *
     * @mbggenerated Thu Nov 09 10:57:41 CST 2017
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uf20_dim_branch.category
     *
     * @param category the value for uf20_dim_branch.category
     *
     * @mbggenerated Thu Nov 09 10:57:41 CST 2017
     */
    public void setCategory(String category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uf20_dim_branch.merge_no
     *
     * @return the value of uf20_dim_branch.merge_no
     *
     * @mbggenerated Thu Nov 09 10:57:41 CST 2017
     */
    public String getMerge_no() {
        return merge_no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uf20_dim_branch.merge_no
     *
     * @param merge_no the value for uf20_dim_branch.merge_no
     *
     * @mbggenerated Thu Nov 09 10:57:41 CST 2017
     */
    public void setMerge_no(String merge_no) {
        this.merge_no = merge_no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uf20_dim_branch.update_time
     *
     * @return the value of uf20_dim_branch.update_time
     *
     * @mbggenerated Thu Nov 09 10:57:41 CST 2017
     */
    public Integer getUpdate_time() {
        return update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uf20_dim_branch.update_time
     *
     * @param update_time the value for uf20_dim_branch.update_time
     *
     * @mbggenerated Thu Nov 09 10:57:41 CST 2017
     */
    public void setUpdate_time(Integer update_time) {
        this.update_time = update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uf20_dim_branch.remark
     *
     * @return the value of uf20_dim_branch.remark
     *
     * @mbggenerated Thu Nov 09 10:57:41 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uf20_dim_branch.remark
     *
     * @param remark the value for uf20_dim_branch.remark
     *
     * @mbggenerated Thu Nov 09 10:57:41 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}