package com.ctsec.model.jf;

public class DimDate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uf20_dim_date.day_id
     *
     * @mbggenerated Thu Jan 11 16:35:07 CST 2018
     */
    private Integer day_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uf20_dim_date.trade_mark
     *
     * @mbggenerated Thu Jan 11 16:35:07 CST 2018
     */
    private String trade_mark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uf20_dim_date.week_id
     *
     * @mbggenerated Thu Jan 11 16:35:07 CST 2018
     */
    private String week_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uf20_dim_date.month_id
     *
     * @mbggenerated Thu Jan 11 16:35:07 CST 2018
     */
    private String month_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uf20_dim_date.quarter_id
     *
     * @mbggenerated Thu Jan 11 16:35:07 CST 2018
     */
    private String quarter_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uf20_dim_date.year_id
     *
     * @mbggenerated Thu Jan 11 16:35:07 CST 2018
     */
    private String year_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uf20_dim_date
     *
     * @mbggenerated Thu Jan 11 16:35:07 CST 2018
     */
    public DimDate(Integer day_id, String trade_mark, String week_id, String month_id, String quarter_id, String year_id) {
        this.day_id = day_id;
        this.trade_mark = trade_mark;
        this.week_id = week_id;
        this.month_id = month_id;
        this.quarter_id = quarter_id;
        this.year_id = year_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uf20_dim_date
     *
     * @mbggenerated Thu Jan 11 16:35:07 CST 2018
     */
    public DimDate() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uf20_dim_date.day_id
     *
     * @return the value of uf20_dim_date.day_id
     *
     * @mbggenerated Thu Jan 11 16:35:07 CST 2018
     */
    public Integer getDay_id() {
        return day_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uf20_dim_date.day_id
     *
     * @param day_id the value for uf20_dim_date.day_id
     *
     * @mbggenerated Thu Jan 11 16:35:07 CST 2018
     */
    public void setDay_id(Integer day_id) {
        this.day_id = day_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uf20_dim_date.trade_mark
     *
     * @return the value of uf20_dim_date.trade_mark
     *
     * @mbggenerated Thu Jan 11 16:35:07 CST 2018
     */
    public String getTrade_mark() {
        return trade_mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uf20_dim_date.trade_mark
     *
     * @param trade_mark the value for uf20_dim_date.trade_mark
     *
     * @mbggenerated Thu Jan 11 16:35:07 CST 2018
     */
    public void setTrade_mark(String trade_mark) {
        this.trade_mark = trade_mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uf20_dim_date.week_id
     *
     * @return the value of uf20_dim_date.week_id
     *
     * @mbggenerated Thu Jan 11 16:35:07 CST 2018
     */
    public String getWeek_id() {
        return week_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uf20_dim_date.week_id
     *
     * @param week_id the value for uf20_dim_date.week_id
     *
     * @mbggenerated Thu Jan 11 16:35:07 CST 2018
     */
    public void setWeek_id(String week_id) {
        this.week_id = week_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uf20_dim_date.month_id
     *
     * @return the value of uf20_dim_date.month_id
     *
     * @mbggenerated Thu Jan 11 16:35:07 CST 2018
     */
    public String getMonth_id() {
        return month_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uf20_dim_date.month_id
     *
     * @param month_id the value for uf20_dim_date.month_id
     *
     * @mbggenerated Thu Jan 11 16:35:07 CST 2018
     */
    public void setMonth_id(String month_id) {
        this.month_id = month_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uf20_dim_date.quarter_id
     *
     * @return the value of uf20_dim_date.quarter_id
     *
     * @mbggenerated Thu Jan 11 16:35:07 CST 2018
     */
    public String getQuarter_id() {
        return quarter_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uf20_dim_date.quarter_id
     *
     * @param quarter_id the value for uf20_dim_date.quarter_id
     *
     * @mbggenerated Thu Jan 11 16:35:07 CST 2018
     */
    public void setQuarter_id(String quarter_id) {
        this.quarter_id = quarter_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uf20_dim_date.year_id
     *
     * @return the value of uf20_dim_date.year_id
     *
     * @mbggenerated Thu Jan 11 16:35:07 CST 2018
     */
    public String getYear_id() {
        return year_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uf20_dim_date.year_id
     *
     * @param year_id the value for uf20_dim_date.year_id
     *
     * @mbggenerated Thu Jan 11 16:35:07 CST 2018
     */
    public void setYear_id(String year_id) {
        this.year_id = year_id;
    }
}