package com.ctsec.model.jf;

public class ExcelImportConfig {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column excel_import_config.id
     *
     * @mbggenerated Mon Dec 25 13:02:18 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column excel_import_config.category1
     *
     * @mbggenerated Mon Dec 25 13:02:18 CST 2017
     */
    private String category1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column excel_import_config.category2
     *
     * @mbggenerated Mon Dec 25 13:02:18 CST 2017
     */
    private String category2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column excel_import_config.sample_path
     *
     * @mbggenerated Mon Dec 25 13:02:18 CST 2017
     */
    private String sample_path;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column excel_import_config.target_table
     *
     * @mbggenerated Mon Dec 25 13:02:18 CST 2017
     */
    private String target_table;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table excel_import_config
     *
     * @mbggenerated Mon Dec 25 13:02:18 CST 2017
     */
    public ExcelImportConfig(Integer id, String category1, String category2, String sample_path, String target_table) {
        this.id = id;
        this.category1 = category1;
        this.category2 = category2;
        this.sample_path = sample_path;
        this.target_table = target_table;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table excel_import_config
     *
     * @mbggenerated Mon Dec 25 13:02:18 CST 2017
     */
    public ExcelImportConfig() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column excel_import_config.id
     *
     * @return the value of excel_import_config.id
     *
     * @mbggenerated Mon Dec 25 13:02:18 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column excel_import_config.id
     *
     * @param id the value for excel_import_config.id
     *
     * @mbggenerated Mon Dec 25 13:02:18 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column excel_import_config.category1
     *
     * @return the value of excel_import_config.category1
     *
     * @mbggenerated Mon Dec 25 13:02:18 CST 2017
     */
    public String getCategory1() {
        return category1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column excel_import_config.category1
     *
     * @param category1 the value for excel_import_config.category1
     *
     * @mbggenerated Mon Dec 25 13:02:18 CST 2017
     */
    public void setCategory1(String category1) {
        this.category1 = category1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column excel_import_config.category2
     *
     * @return the value of excel_import_config.category2
     *
     * @mbggenerated Mon Dec 25 13:02:18 CST 2017
     */
    public String getCategory2() {
        return category2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column excel_import_config.category2
     *
     * @param category2 the value for excel_import_config.category2
     *
     * @mbggenerated Mon Dec 25 13:02:18 CST 2017
     */
    public void setCategory2(String category2) {
        this.category2 = category2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column excel_import_config.sample_path
     *
     * @return the value of excel_import_config.sample_path
     *
     * @mbggenerated Mon Dec 25 13:02:18 CST 2017
     */
    public String getSample_path() {
        return sample_path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column excel_import_config.sample_path
     *
     * @param sample_path the value for excel_import_config.sample_path
     *
     * @mbggenerated Mon Dec 25 13:02:18 CST 2017
     */
    public void setSample_path(String sample_path) {
        this.sample_path = sample_path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column excel_import_config.target_table
     *
     * @return the value of excel_import_config.target_table
     *
     * @mbggenerated Mon Dec 25 13:02:18 CST 2017
     */
    public String getTarget_table() {
        return target_table;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column excel_import_config.target_table
     *
     * @param target_table the value for excel_import_config.target_table
     *
     * @mbggenerated Mon Dec 25 13:02:18 CST 2017
     */
    public void setTarget_table(String target_table) {
        this.target_table = target_table;
    }
}