package com.ctsec.model.jf;

public class IndexInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_info.index_id
     *
     * @mbggenerated Wed Nov 15 19:25:36 CST 2017
     */
    private Integer index_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_info.system_id
     *
     * @mbggenerated Wed Nov 15 19:25:36 CST 2017
     */
    private String system_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_info.system_desc
     *
     * @mbggenerated Wed Nov 15 19:25:36 CST 2017
     */
    private String system_desc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_info.menu_id
     *
     * @mbggenerated Wed Nov 15 19:25:36 CST 2017
     */
    private String menu_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_info.menu_desc
     *
     * @mbggenerated Wed Nov 15 19:25:36 CST 2017
     */
    private String menu_desc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_info.class_id
     *
     * @mbggenerated Wed Nov 15 19:25:36 CST 2017
     */
    private String class_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_info.class_desc
     *
     * @mbggenerated Wed Nov 15 19:25:36 CST 2017
     */
    private String class_desc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_info.category_id
     *
     * @mbggenerated Wed Nov 15 19:25:36 CST 2017
     */
    private String category_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_info.category_desc
     *
     * @mbggenerated Wed Nov 15 19:25:36 CST 2017
     */
    private String category_desc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_info.index_desc
     *
     * @mbggenerated Wed Nov 15 19:25:36 CST 2017
     */
    private String index_desc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_info.is_report
     *
     * @mbggenerated Wed Nov 15 19:25:36 CST 2017
     */
    private String is_report;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_info.report_id
     *
     * @mbggenerated Wed Nov 15 19:25:36 CST 2017
     */
    private Integer report_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_info.index_info
     *
     * @mbggenerated Wed Nov 15 19:25:36 CST 2017
     */
    private String index_info;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table index_info
     *
     * @mbggenerated Wed Nov 15 19:25:36 CST 2017
     */
    public IndexInfo(Integer index_id, String system_id, String system_desc, String menu_id, String menu_desc, String class_id, String class_desc, String category_id, String category_desc, String index_desc, String is_report, Integer report_id, String index_info) {
        this.index_id = index_id;
        this.system_id = system_id;
        this.system_desc = system_desc;
        this.menu_id = menu_id;
        this.menu_desc = menu_desc;
        this.class_id = class_id;
        this.class_desc = class_desc;
        this.category_id = category_id;
        this.category_desc = category_desc;
        this.index_desc = index_desc;
        this.is_report = is_report;
        this.report_id = report_id;
        this.index_info = index_info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table index_info
     *
     * @mbggenerated Wed Nov 15 19:25:36 CST 2017
     */
    public IndexInfo() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_info.index_id
     *
     * @return the value of index_info.index_id
     *
     * @mbggenerated Wed Nov 15 19:25:36 CST 2017
     */
    public Integer getIndex_id() {
        return index_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_info.index_id
     *
     * @param index_id the value for index_info.index_id
     *
     * @mbggenerated Wed Nov 15 19:25:36 CST 2017
     */
    public void setIndex_id(Integer index_id) {
        this.index_id = index_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_info.system_id
     *
     * @return the value of index_info.system_id
     *
     * @mbggenerated Wed Nov 15 19:25:36 CST 2017
     */
    public String getSystem_id() {
        return system_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_info.system_id
     *
     * @param system_id the value for index_info.system_id
     *
     * @mbggenerated Wed Nov 15 19:25:36 CST 2017
     */
    public void setSystem_id(String system_id) {
        this.system_id = system_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_info.system_desc
     *
     * @return the value of index_info.system_desc
     *
     * @mbggenerated Wed Nov 15 19:25:36 CST 2017
     */
    public String getSystem_desc() {
        return system_desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_info.system_desc
     *
     * @param system_desc the value for index_info.system_desc
     *
     * @mbggenerated Wed Nov 15 19:25:36 CST 2017
     */
    public void setSystem_desc(String system_desc) {
        this.system_desc = system_desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_info.menu_id
     *
     * @return the value of index_info.menu_id
     *
     * @mbggenerated Wed Nov 15 19:25:36 CST 2017
     */
    public String getMenu_id() {
        return menu_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_info.menu_id
     *
     * @param menu_id the value for index_info.menu_id
     *
     * @mbggenerated Wed Nov 15 19:25:36 CST 2017
     */
    public void setMenu_id(String menu_id) {
        this.menu_id = menu_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_info.menu_desc
     *
     * @return the value of index_info.menu_desc
     *
     * @mbggenerated Wed Nov 15 19:25:36 CST 2017
     */
    public String getMenu_desc() {
        return menu_desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_info.menu_desc
     *
     * @param menu_desc the value for index_info.menu_desc
     *
     * @mbggenerated Wed Nov 15 19:25:36 CST 2017
     */
    public void setMenu_desc(String menu_desc) {
        this.menu_desc = menu_desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_info.class_id
     *
     * @return the value of index_info.class_id
     *
     * @mbggenerated Wed Nov 15 19:25:36 CST 2017
     */
    public String getClass_id() {
        return class_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_info.class_id
     *
     * @param class_id the value for index_info.class_id
     *
     * @mbggenerated Wed Nov 15 19:25:36 CST 2017
     */
    public void setClass_id(String class_id) {
        this.class_id = class_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_info.class_desc
     *
     * @return the value of index_info.class_desc
     *
     * @mbggenerated Wed Nov 15 19:25:36 CST 2017
     */
    public String getClass_desc() {
        return class_desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_info.class_desc
     *
     * @param class_desc the value for index_info.class_desc
     *
     * @mbggenerated Wed Nov 15 19:25:36 CST 2017
     */
    public void setClass_desc(String class_desc) {
        this.class_desc = class_desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_info.category_id
     *
     * @return the value of index_info.category_id
     *
     * @mbggenerated Wed Nov 15 19:25:36 CST 2017
     */
    public String getCategory_id() {
        return category_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_info.category_id
     *
     * @param category_id the value for index_info.category_id
     *
     * @mbggenerated Wed Nov 15 19:25:36 CST 2017
     */
    public void setCategory_id(String category_id) {
        this.category_id = category_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_info.category_desc
     *
     * @return the value of index_info.category_desc
     *
     * @mbggenerated Wed Nov 15 19:25:36 CST 2017
     */
    public String getCategory_desc() {
        return category_desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_info.category_desc
     *
     * @param category_desc the value for index_info.category_desc
     *
     * @mbggenerated Wed Nov 15 19:25:36 CST 2017
     */
    public void setCategory_desc(String category_desc) {
        this.category_desc = category_desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_info.index_desc
     *
     * @return the value of index_info.index_desc
     *
     * @mbggenerated Wed Nov 15 19:25:36 CST 2017
     */
    public String getIndex_desc() {
        return index_desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_info.index_desc
     *
     * @param index_desc the value for index_info.index_desc
     *
     * @mbggenerated Wed Nov 15 19:25:36 CST 2017
     */
    public void setIndex_desc(String index_desc) {
        this.index_desc = index_desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_info.is_report
     *
     * @return the value of index_info.is_report
     *
     * @mbggenerated Wed Nov 15 19:25:36 CST 2017
     */
    public String getIs_report() {
        return is_report;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_info.is_report
     *
     * @param is_report the value for index_info.is_report
     *
     * @mbggenerated Wed Nov 15 19:25:36 CST 2017
     */
    public void setIs_report(String is_report) {
        this.is_report = is_report;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_info.report_id
     *
     * @return the value of index_info.report_id
     *
     * @mbggenerated Wed Nov 15 19:25:36 CST 2017
     */
    public Integer getReport_id() {
        return report_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_info.report_id
     *
     * @param report_id the value for index_info.report_id
     *
     * @mbggenerated Wed Nov 15 19:25:36 CST 2017
     */
    public void setReport_id(Integer report_id) {
        this.report_id = report_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_info.index_info
     *
     * @return the value of index_info.index_info
     *
     * @mbggenerated Wed Nov 15 19:25:36 CST 2017
     */
    public String getIndex_info() {
        return index_info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_info.index_info
     *
     * @param index_info the value for index_info.index_info
     *
     * @mbggenerated Wed Nov 15 19:25:36 CST 2017
     */
    public void setIndex_info(String index_info) {
        this.index_info = index_info;
    }
}