package com.ctsec.model.jf;

import java.util.Date;

public class KapCubeInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kap_cube_info.init_date
     *
     * @mbggenerated Mon Dec 18 19:30:19 CST 2017
     */
    private Integer init_date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kap_cube_info.cube_name
     *
     * @mbggenerated Mon Dec 18 19:30:19 CST 2017
     */
    private String cube_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kap_cube_info.project_name
     *
     * @mbggenerated Mon Dec 18 19:30:19 CST 2017
     */
    private String project_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kap_cube_info.model_name
     *
     * @mbggenerated Mon Dec 18 19:30:19 CST 2017
     */
    private String model_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kap_cube_info.cube_owner
     *
     * @mbggenerated Mon Dec 18 19:30:19 CST 2017
     */
    private String cube_owner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kap_cube_info.cube_end_time
     *
     * @mbggenerated Mon Dec 18 19:30:19 CST 2017
     */
    private Date cube_end_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kap_cube_info.update_time
     *
     * @mbggenerated Mon Dec 18 19:30:19 CST 2017
     */
    private Date update_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kap_cube_info
     *
     * @mbggenerated Mon Dec 18 19:30:19 CST 2017
     */
    public KapCubeInfo(Integer init_date, String cube_name, String project_name, String model_name, String cube_owner, Date cube_end_time, Date update_time) {
        this.init_date = init_date;
        this.cube_name = cube_name;
        this.project_name = project_name;
        this.model_name = model_name;
        this.cube_owner = cube_owner;
        this.cube_end_time = cube_end_time;
        this.update_time = update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kap_cube_info
     *
     * @mbggenerated Mon Dec 18 19:30:19 CST 2017
     */
    public KapCubeInfo() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kap_cube_info.init_date
     *
     * @return the value of kap_cube_info.init_date
     *
     * @mbggenerated Mon Dec 18 19:30:19 CST 2017
     */
    public Integer getInit_date() {
        return init_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kap_cube_info.init_date
     *
     * @param init_date the value for kap_cube_info.init_date
     *
     * @mbggenerated Mon Dec 18 19:30:19 CST 2017
     */
    public void setInit_date(Integer init_date) {
        this.init_date = init_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kap_cube_info.cube_name
     *
     * @return the value of kap_cube_info.cube_name
     *
     * @mbggenerated Mon Dec 18 19:30:19 CST 2017
     */
    public String getCube_name() {
        return cube_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kap_cube_info.cube_name
     *
     * @param cube_name the value for kap_cube_info.cube_name
     *
     * @mbggenerated Mon Dec 18 19:30:19 CST 2017
     */
    public void setCube_name(String cube_name) {
        this.cube_name = cube_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kap_cube_info.project_name
     *
     * @return the value of kap_cube_info.project_name
     *
     * @mbggenerated Mon Dec 18 19:30:19 CST 2017
     */
    public String getProject_name() {
        return project_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kap_cube_info.project_name
     *
     * @param project_name the value for kap_cube_info.project_name
     *
     * @mbggenerated Mon Dec 18 19:30:19 CST 2017
     */
    public void setProject_name(String project_name) {
        this.project_name = project_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kap_cube_info.model_name
     *
     * @return the value of kap_cube_info.model_name
     *
     * @mbggenerated Mon Dec 18 19:30:19 CST 2017
     */
    public String getModel_name() {
        return model_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kap_cube_info.model_name
     *
     * @param model_name the value for kap_cube_info.model_name
     *
     * @mbggenerated Mon Dec 18 19:30:19 CST 2017
     */
    public void setModel_name(String model_name) {
        this.model_name = model_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kap_cube_info.cube_owner
     *
     * @return the value of kap_cube_info.cube_owner
     *
     * @mbggenerated Mon Dec 18 19:30:19 CST 2017
     */
    public String getCube_owner() {
        return cube_owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kap_cube_info.cube_owner
     *
     * @param cube_owner the value for kap_cube_info.cube_owner
     *
     * @mbggenerated Mon Dec 18 19:30:19 CST 2017
     */
    public void setCube_owner(String cube_owner) {
        this.cube_owner = cube_owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kap_cube_info.cube_end_time
     *
     * @return the value of kap_cube_info.cube_end_time
     *
     * @mbggenerated Mon Dec 18 19:30:19 CST 2017
     */
    public Date getCube_end_time() {
        return cube_end_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kap_cube_info.cube_end_time
     *
     * @param cube_end_time the value for kap_cube_info.cube_end_time
     *
     * @mbggenerated Mon Dec 18 19:30:19 CST 2017
     */
    public void setCube_end_time(Date cube_end_time) {
        this.cube_end_time = cube_end_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kap_cube_info.update_time
     *
     * @return the value of kap_cube_info.update_time
     *
     * @mbggenerated Mon Dec 18 19:30:19 CST 2017
     */
    public Date getUpdate_time() {
        return update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kap_cube_info.update_time
     *
     * @param update_time the value for kap_cube_info.update_time
     *
     * @mbggenerated Mon Dec 18 19:30:19 CST 2017
     */
    public void setUpdate_time(Date update_time) {
        this.update_time = update_time;
    }
}