package com.ctsec.model.jf;

public class KLine {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jy_k_day.init_date
     *
     * @mbggenerated Thu Nov 02 14:36:21 CST 2017
     */
    private Integer init_date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jy_k_day.secu_code
     *
     * @mbggenerated Thu Nov 02 14:36:21 CST 2017
     */
    private String secu_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jy_k_day.open_price
     *
     * @mbggenerated Thu Nov 02 14:36:21 CST 2017
     */
    private Double open_price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jy_k_day.high_price
     *
     * @mbggenerated Thu Nov 02 14:36:21 CST 2017
     */
    private Double high_price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jy_k_day.low_price
     *
     * @mbggenerated Thu Nov 02 14:36:21 CST 2017
     */
    private Double low_price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jy_k_day.close_price
     *
     * @mbggenerated Thu Nov 02 14:36:21 CST 2017
     */
    private Double close_price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jy_k_day.update_date
     *
     * @mbggenerated Thu Nov 02 14:36:21 CST 2017
     */
    private Integer update_date;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jy_k_day
     *
     * @mbggenerated Thu Nov 02 14:36:21 CST 2017
     */
    public KLine(Integer init_date, String secu_code, Double open_price, Double high_price, Double low_price, Double close_price, Integer update_date) {
        this.init_date = init_date;
        this.secu_code = secu_code;
        this.open_price = open_price;
        this.high_price = high_price;
        this.low_price = low_price;
        this.close_price = close_price;
        this.update_date = update_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jy_k_day
     *
     * @mbggenerated Thu Nov 02 14:36:21 CST 2017
     */
    public KLine() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jy_k_day.init_date
     *
     * @return the value of jy_k_day.init_date
     *
     * @mbggenerated Thu Nov 02 14:36:21 CST 2017
     */
    public Integer getInit_date() {
        return init_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jy_k_day.init_date
     *
     * @param init_date the value for jy_k_day.init_date
     *
     * @mbggenerated Thu Nov 02 14:36:21 CST 2017
     */
    public void setInit_date(Integer init_date) {
        this.init_date = init_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jy_k_day.secu_code
     *
     * @return the value of jy_k_day.secu_code
     *
     * @mbggenerated Thu Nov 02 14:36:21 CST 2017
     */
    public String getSecu_code() {
        return secu_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jy_k_day.secu_code
     *
     * @param secu_code the value for jy_k_day.secu_code
     *
     * @mbggenerated Thu Nov 02 14:36:21 CST 2017
     */
    public void setSecu_code(String secu_code) {
        this.secu_code = secu_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jy_k_day.open_price
     *
     * @return the value of jy_k_day.open_price
     *
     * @mbggenerated Thu Nov 02 14:36:21 CST 2017
     */
    public Double getOpen_price() {
        return open_price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jy_k_day.open_price
     *
     * @param open_price the value for jy_k_day.open_price
     *
     * @mbggenerated Thu Nov 02 14:36:21 CST 2017
     */
    public void setOpen_price(Double open_price) {
        this.open_price = open_price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jy_k_day.high_price
     *
     * @return the value of jy_k_day.high_price
     *
     * @mbggenerated Thu Nov 02 14:36:21 CST 2017
     */
    public Double getHigh_price() {
        return high_price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jy_k_day.high_price
     *
     * @param high_price the value for jy_k_day.high_price
     *
     * @mbggenerated Thu Nov 02 14:36:21 CST 2017
     */
    public void setHigh_price(Double high_price) {
        this.high_price = high_price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jy_k_day.low_price
     *
     * @return the value of jy_k_day.low_price
     *
     * @mbggenerated Thu Nov 02 14:36:21 CST 2017
     */
    public Double getLow_price() {
        return low_price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jy_k_day.low_price
     *
     * @param low_price the value for jy_k_day.low_price
     *
     * @mbggenerated Thu Nov 02 14:36:21 CST 2017
     */
    public void setLow_price(Double low_price) {
        this.low_price = low_price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jy_k_day.close_price
     *
     * @return the value of jy_k_day.close_price
     *
     * @mbggenerated Thu Nov 02 14:36:21 CST 2017
     */
    public Double getClose_price() {
        return close_price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jy_k_day.close_price
     *
     * @param close_price the value for jy_k_day.close_price
     *
     * @mbggenerated Thu Nov 02 14:36:21 CST 2017
     */
    public void setClose_price(Double close_price) {
        this.close_price = close_price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jy_k_day.update_date
     *
     * @return the value of jy_k_day.update_date
     *
     * @mbggenerated Thu Nov 02 14:36:21 CST 2017
     */
    public Integer getUpdate_date() {
        return update_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jy_k_day.update_date
     *
     * @param update_date the value for jy_k_day.update_date
     *
     * @mbggenerated Thu Nov 02 14:36:21 CST 2017
     */
    public void setUpdate_date(Integer update_date) {
        this.update_date = update_date;
    }
}