package com.ctsec.model.jf;

public class ManualAdjust {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manual_adjust.branch_code
     *
     * @mbggenerated Mon Dec 25 14:02:41 CST 2017
     */
    private Integer branch_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manual_adjust.adjust_time
     *
     * @mbggenerated Mon Dec 25 14:02:41 CST 2017
     */
    private Integer adjust_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manual_adjust.adjust_amount
     *
     * @mbggenerated Mon Dec 25 14:02:41 CST 2017
     */
    private Double adjust_amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manual_adjust.adjust_granularity
     *
     * @mbggenerated Mon Dec 25 14:02:41 CST 2017
     */
    private Integer adjust_granularity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manual_adjust.adjust_item
     *
     * @mbggenerated Mon Dec 25 14:02:41 CST 2017
     */
    private String adjust_item;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manual_adjust.update_time
     *
     * @mbggenerated Mon Dec 25 14:02:41 CST 2017
     */
    private Integer update_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manual_adjust
     *
     * @mbggenerated Mon Dec 25 14:02:41 CST 2017
     */
    public ManualAdjust(Integer branch_code, Integer adjust_time, Double adjust_amount, Integer adjust_granularity, String adjust_item, Integer update_time) {
        this.branch_code = branch_code;
        this.adjust_time = adjust_time;
        this.adjust_amount = adjust_amount;
        this.adjust_granularity = adjust_granularity;
        this.adjust_item = adjust_item;
        this.update_time = update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manual_adjust
     *
     * @mbggenerated Mon Dec 25 14:02:41 CST 2017
     */
    public ManualAdjust() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manual_adjust.branch_code
     *
     * @return the value of manual_adjust.branch_code
     *
     * @mbggenerated Mon Dec 25 14:02:41 CST 2017
     */
    public Integer getBranch_code() {
        return branch_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manual_adjust.branch_code
     *
     * @param branch_code the value for manual_adjust.branch_code
     *
     * @mbggenerated Mon Dec 25 14:02:41 CST 2017
     */
    public void setBranch_code(Integer branch_code) {
        this.branch_code = branch_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manual_adjust.adjust_time
     *
     * @return the value of manual_adjust.adjust_time
     *
     * @mbggenerated Mon Dec 25 14:02:41 CST 2017
     */
    public Integer getAdjust_time() {
        return adjust_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manual_adjust.adjust_time
     *
     * @param adjust_time the value for manual_adjust.adjust_time
     *
     * @mbggenerated Mon Dec 25 14:02:41 CST 2017
     */
    public void setAdjust_time(Integer adjust_time) {
        this.adjust_time = adjust_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manual_adjust.adjust_amount
     *
     * @return the value of manual_adjust.adjust_amount
     *
     * @mbggenerated Mon Dec 25 14:02:41 CST 2017
     */
    public Double getAdjust_amount() {
        return adjust_amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manual_adjust.adjust_amount
     *
     * @param adjust_amount the value for manual_adjust.adjust_amount
     *
     * @mbggenerated Mon Dec 25 14:02:41 CST 2017
     */
    public void setAdjust_amount(Double adjust_amount) {
        this.adjust_amount = adjust_amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manual_adjust.adjust_granularity
     *
     * @return the value of manual_adjust.adjust_granularity
     *
     * @mbggenerated Mon Dec 25 14:02:41 CST 2017
     */
    public Integer getAdjust_granularity() {
        return adjust_granularity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manual_adjust.adjust_granularity
     *
     * @param adjust_granularity the value for manual_adjust.adjust_granularity
     *
     * @mbggenerated Mon Dec 25 14:02:41 CST 2017
     */
    public void setAdjust_granularity(Integer adjust_granularity) {
        this.adjust_granularity = adjust_granularity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manual_adjust.adjust_item
     *
     * @return the value of manual_adjust.adjust_item
     *
     * @mbggenerated Mon Dec 25 14:02:41 CST 2017
     */
    public String getAdjust_item() {
        return adjust_item;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manual_adjust.adjust_item
     *
     * @param adjust_item the value for manual_adjust.adjust_item
     *
     * @mbggenerated Mon Dec 25 14:02:41 CST 2017
     */
    public void setAdjust_item(String adjust_item) {
        this.adjust_item = adjust_item;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manual_adjust.update_time
     *
     * @return the value of manual_adjust.update_time
     *
     * @mbggenerated Mon Dec 25 14:02:41 CST 2017
     */
    public Integer getUpdate_time() {
        return update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manual_adjust.update_time
     *
     * @param update_time the value for manual_adjust.update_time
     *
     * @mbggenerated Mon Dec 25 14:02:41 CST 2017
     */
    public void setUpdate_time(Integer update_time) {
        this.update_time = update_time;
    }
}