package com.ctsec.model.jf;

import java.util.Date;

public class RelationGroup {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relation_group.id
     *
     * @mbggenerated Fri Dec 15 13:24:50 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relation_group.name
     *
     * @mbggenerated Fri Dec 15 13:24:50 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relation_group.is_delete
     *
     * @mbggenerated Fri Dec 15 13:24:50 CST 2017
     */
    private String is_delete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relation_group.create_time
     *
     * @mbggenerated Fri Dec 15 13:24:50 CST 2017
     */
    private Date create_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relation_group.update_time
     *
     * @mbggenerated Fri Dec 15 13:24:50 CST 2017
     */
    private Date update_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_group
     *
     * @mbggenerated Fri Dec 15 13:24:50 CST 2017
     */
    public RelationGroup(Long id, String name, String is_delete, Date create_time, Date update_time) {
        this.id = id;
        this.name = name;
        this.is_delete = is_delete;
        this.create_time = create_time;
        this.update_time = update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_group
     *
     * @mbggenerated Fri Dec 15 13:24:50 CST 2017
     */
    public RelationGroup() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relation_group.id
     *
     * @return the value of relation_group.id
     *
     * @mbggenerated Fri Dec 15 13:24:50 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relation_group.id
     *
     * @param id the value for relation_group.id
     *
     * @mbggenerated Fri Dec 15 13:24:50 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relation_group.name
     *
     * @return the value of relation_group.name
     *
     * @mbggenerated Fri Dec 15 13:24:50 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relation_group.name
     *
     * @param name the value for relation_group.name
     *
     * @mbggenerated Fri Dec 15 13:24:50 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relation_group.is_delete
     *
     * @return the value of relation_group.is_delete
     *
     * @mbggenerated Fri Dec 15 13:24:50 CST 2017
     */
    public String getIs_delete() {
        return is_delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relation_group.is_delete
     *
     * @param is_delete the value for relation_group.is_delete
     *
     * @mbggenerated Fri Dec 15 13:24:50 CST 2017
     */
    public void setIs_delete(String is_delete) {
        this.is_delete = is_delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relation_group.create_time
     *
     * @return the value of relation_group.create_time
     *
     * @mbggenerated Fri Dec 15 13:24:50 CST 2017
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relation_group.create_time
     *
     * @param create_time the value for relation_group.create_time
     *
     * @mbggenerated Fri Dec 15 13:24:50 CST 2017
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relation_group.update_time
     *
     * @return the value of relation_group.update_time
     *
     * @mbggenerated Fri Dec 15 13:24:50 CST 2017
     */
    public Date getUpdate_time() {
        return update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relation_group.update_time
     *
     * @param update_time the value for relation_group.update_time
     *
     * @mbggenerated Fri Dec 15 13:24:50 CST 2017
     */
    public void setUpdate_time(Date update_time) {
        this.update_time = update_time;
    }
}