package com.ctsec.model.jf;

public class ReportIndex {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_index.id
     *
     * @mbggenerated Tue Nov 14 09:23:45 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_index.report_id
     *
     * @mbggenerated Tue Nov 14 09:23:45 CST 2017
     */
    private Long report_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_index.index_id
     *
     * @mbggenerated Tue Nov 14 09:23:45 CST 2017
     */
    private String index_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_index.field_name
     *
     * @mbggenerated Tue Nov 14 09:23:45 CST 2017
     */
    private String field_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_index.name
     *
     * @mbggenerated Tue Nov 14 09:23:45 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_index.is_default
     *
     * @mbggenerated Tue Nov 14 09:23:45 CST 2017
     */
    private String is_default;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_index.info
     *
     * @mbggenerated Tue Nov 14 09:23:45 CST 2017
     */
    private String info;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_index.unit
     *
     * @mbggenerated Tue Nov 14 09:23:45 CST 2017
     */
    private String unit;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_index
     *
     * @mbggenerated Tue Nov 14 09:23:45 CST 2017
     */
    public ReportIndex(Long id, Long report_id, String index_id, String field_name, String name, String is_default, String info, String unit) {
        this.id = id;
        this.report_id = report_id;
        this.index_id = index_id;
        this.field_name = field_name;
        this.name = name;
        this.is_default = is_default;
        this.info = info;
        this.unit = unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_index
     *
     * @mbggenerated Tue Nov 14 09:23:45 CST 2017
     */
    public ReportIndex() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_index.id
     *
     * @return the value of report_index.id
     *
     * @mbggenerated Tue Nov 14 09:23:45 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_index.id
     *
     * @param id the value for report_index.id
     *
     * @mbggenerated Tue Nov 14 09:23:45 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_index.report_id
     *
     * @return the value of report_index.report_id
     *
     * @mbggenerated Tue Nov 14 09:23:45 CST 2017
     */
    public Long getReport_id() {
        return report_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_index.report_id
     *
     * @param report_id the value for report_index.report_id
     *
     * @mbggenerated Tue Nov 14 09:23:45 CST 2017
     */
    public void setReport_id(Long report_id) {
        this.report_id = report_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_index.index_id
     *
     * @return the value of report_index.index_id
     *
     * @mbggenerated Tue Nov 14 09:23:45 CST 2017
     */
    public String getIndex_id() {
        return index_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_index.index_id
     *
     * @param index_id the value for report_index.index_id
     *
     * @mbggenerated Tue Nov 14 09:23:45 CST 2017
     */
    public void setIndex_id(String index_id) {
        this.index_id = index_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_index.field_name
     *
     * @return the value of report_index.field_name
     *
     * @mbggenerated Tue Nov 14 09:23:45 CST 2017
     */
    public String getField_name() {
        return field_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_index.field_name
     *
     * @param field_name the value for report_index.field_name
     *
     * @mbggenerated Tue Nov 14 09:23:45 CST 2017
     */
    public void setField_name(String field_name) {
        this.field_name = field_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_index.name
     *
     * @return the value of report_index.name
     *
     * @mbggenerated Tue Nov 14 09:23:45 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_index.name
     *
     * @param name the value for report_index.name
     *
     * @mbggenerated Tue Nov 14 09:23:45 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_index.is_default
     *
     * @return the value of report_index.is_default
     *
     * @mbggenerated Tue Nov 14 09:23:45 CST 2017
     */
    public String getIs_default() {
        return is_default;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_index.is_default
     *
     * @param is_default the value for report_index.is_default
     *
     * @mbggenerated Tue Nov 14 09:23:45 CST 2017
     */
    public void setIs_default(String is_default) {
        this.is_default = is_default;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_index.info
     *
     * @return the value of report_index.info
     *
     * @mbggenerated Tue Nov 14 09:23:45 CST 2017
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_index.unit
     *
     * @param unit the value for report_index.unit
     *
     * @mbggenerated Tue Nov 14 09:23:45 CST 2017
     */
    public void setUnit(String unit) {
        this.unit = unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_index.unit
     *
     * @return the value of report_index.unit
     *
     * @mbggenerated Tue Nov 14 09:23:45 CST 2017
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_index.info
     *
     * @param info the value for report_index.info
     *
     * @mbggenerated Tue Nov 14 09:23:45 CST 2017
     */
    public void setInfo(String info) {
        this.info = info;
    }
}