package com.ctsec.model.jf;

public class SecuCompany {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uf20_dim_secucompany.company_id
     *
     * @mbggenerated Tue Dec 12 20:35:56 CST 2017
     */
    private Integer company_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uf20_dim_secucompany.company_name
     *
     * @mbggenerated Tue Dec 12 20:35:56 CST 2017
     */
    private String company_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uf20_dim_secucompany.sac_id
     *
     * @mbggenerated Tue Dec 12 20:35:56 CST 2017
     */
    private Integer sac_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uf20_dim_secucompany.update_date
     *
     * @mbggenerated Tue Dec 12 20:35:56 CST 2017
     */
    private Integer update_date;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uf20_dim_secucompany
     *
     * @mbggenerated Tue Dec 12 20:35:56 CST 2017
     */
    public SecuCompany(Integer company_id, String company_name, Integer sac_id, Integer update_date) {
        this.company_id = company_id;
        this.company_name = company_name;
        this.sac_id = sac_id;
        this.update_date = update_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uf20_dim_secucompany
     *
     * @mbggenerated Tue Dec 12 20:35:56 CST 2017
     */
    public SecuCompany() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uf20_dim_secucompany.company_id
     *
     * @return the value of uf20_dim_secucompany.company_id
     *
     * @mbggenerated Tue Dec 12 20:35:56 CST 2017
     */
    public Integer getCompany_id() {
        return company_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uf20_dim_secucompany.company_id
     *
     * @param company_id the value for uf20_dim_secucompany.company_id
     *
     * @mbggenerated Tue Dec 12 20:35:56 CST 2017
     */
    public void setCompany_id(Integer company_id) {
        this.company_id = company_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uf20_dim_secucompany.company_name
     *
     * @return the value of uf20_dim_secucompany.company_name
     *
     * @mbggenerated Tue Dec 12 20:35:56 CST 2017
     */
    public String getCompany_name() {
        return company_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uf20_dim_secucompany.company_name
     *
     * @param company_name the value for uf20_dim_secucompany.company_name
     *
     * @mbggenerated Tue Dec 12 20:35:56 CST 2017
     */
    public void setCompany_name(String company_name) {
        this.company_name = company_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uf20_dim_secucompany.sac_id
     *
     * @return the value of uf20_dim_secucompany.sac_id
     *
     * @mbggenerated Tue Dec 12 20:35:56 CST 2017
     */
    public Integer getSac_id() {
        return sac_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uf20_dim_secucompany.sac_id
     *
     * @param sac_id the value for uf20_dim_secucompany.sac_id
     *
     * @mbggenerated Tue Dec 12 20:35:56 CST 2017
     */
    public void setSac_id(Integer sac_id) {
        this.sac_id = sac_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uf20_dim_secucompany.update_date
     *
     * @return the value of uf20_dim_secucompany.update_date
     *
     * @mbggenerated Tue Dec 12 20:35:56 CST 2017
     */
    public Integer getUpdate_date() {
        return update_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uf20_dim_secucompany.update_date
     *
     * @param update_date the value for uf20_dim_secucompany.update_date
     *
     * @mbggenerated Tue Dec 12 20:35:56 CST 2017
     */
    public void setUpdate_date(Integer update_date) {
        this.update_date = update_date;
    }
}