package com.ctsec.model.jf;

import java.util.Date;

public class TradeStatisticsSh {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_statistics_sh.month_id
     *
     * @mbggenerated Tue Dec 12 16:29:18 CST 2017
     */
    private Integer month_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_statistics_sh.secu_id
     *
     * @mbggenerated Tue Dec 12 16:29:18 CST 2017
     */
    private Integer secu_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_statistics_sh.name
     *
     * @mbggenerated Tue Dec 12 16:29:18 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_statistics_sh.set_num
     *
     * @mbggenerated Tue Dec 12 16:29:18 CST 2017
     */
    private Integer set_num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_statistics_sh.total
     *
     * @mbggenerated Tue Dec 12 16:29:18 CST 2017
     */
    private Double total;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_statistics_sh.stock
     *
     * @mbggenerated Tue Dec 12 16:29:18 CST 2017
     */
    private Double stock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_statistics_sh.fund
     *
     * @mbggenerated Tue Dec 12 16:29:18 CST 2017
     */
    private Double fund;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_statistics_sh.etf
     *
     * @mbggenerated Tue Dec 12 16:29:18 CST 2017
     */
    private Double etf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_statistics_sh.national_debt
     *
     * @mbggenerated Tue Dec 12 16:29:18 CST 2017
     */
    private Double national_debt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_statistics_sh.government_debt
     *
     * @mbggenerated Tue Dec 12 16:29:18 CST 2017
     */
    private Double government_debt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_statistics_sh.company_debt
     *
     * @mbggenerated Tue Dec 12 16:29:18 CST 2017
     */
    private Double company_debt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_statistics_sh.convertible_bond
     *
     * @mbggenerated Tue Dec 12 16:29:18 CST 2017
     */
    private Double convertible_bond;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_statistics_sh.bond_repurchase
     *
     * @mbggenerated Tue Dec 12 16:29:18 CST 2017
     */
    private Double bond_repurchase;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_statistics_sh.warrant
     *
     * @mbggenerated Tue Dec 12 16:29:18 CST 2017
     */
    private Double warrant;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_statistics_sh.update_time
     *
     * @mbggenerated Tue Dec 12 16:29:18 CST 2017
     */
    private Date update_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_statistics_sh
     *
     * @mbggenerated Tue Dec 12 16:29:18 CST 2017
     */
    public TradeStatisticsSh(Integer month_id, Integer secu_id, String name, Integer set_num, Double total, Double stock, Double fund, Double etf, Double national_debt, Double government_debt, Double company_debt, Double convertible_bond, Double bond_repurchase, Double warrant, Date update_time) {
        this.month_id = month_id;
        this.secu_id = secu_id;
        this.name = name;
        this.set_num = set_num;
        this.total = total;
        this.stock = stock;
        this.fund = fund;
        this.etf = etf;
        this.national_debt = national_debt;
        this.government_debt = government_debt;
        this.company_debt = company_debt;
        this.convertible_bond = convertible_bond;
        this.bond_repurchase = bond_repurchase;
        this.warrant = warrant;
        this.update_time = update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_statistics_sh
     *
     * @mbggenerated Tue Dec 12 16:29:18 CST 2017
     */
    public TradeStatisticsSh() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_statistics_sh.month_id
     *
     * @return the value of trade_statistics_sh.month_id
     *
     * @mbggenerated Tue Dec 12 16:29:18 CST 2017
     */
    public Integer getMonth_id() {
        return month_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_statistics_sh.month_id
     *
     * @param month_id the value for trade_statistics_sh.month_id
     *
     * @mbggenerated Tue Dec 12 16:29:18 CST 2017
     */
    public void setMonth_id(Integer month_id) {
        this.month_id = month_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_statistics_sh.secu_id
     *
     * @return the value of trade_statistics_sh.secu_id
     *
     * @mbggenerated Tue Dec 12 16:29:18 CST 2017
     */
    public Integer getSecu_id() {
        return secu_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_statistics_sh.secu_id
     *
     * @param secu_id the value for trade_statistics_sh.secu_id
     *
     * @mbggenerated Tue Dec 12 16:29:18 CST 2017
     */
    public void setSecu_id(Integer secu_id) {
        this.secu_id = secu_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_statistics_sh.name
     *
     * @return the value of trade_statistics_sh.name
     *
     * @mbggenerated Tue Dec 12 16:29:18 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_statistics_sh.name
     *
     * @param name the value for trade_statistics_sh.name
     *
     * @mbggenerated Tue Dec 12 16:29:18 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_statistics_sh.set_num
     *
     * @return the value of trade_statistics_sh.set_num
     *
     * @mbggenerated Tue Dec 12 16:29:18 CST 2017
     */
    public Integer getSet_num() {
        return set_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_statistics_sh.set_num
     *
     * @param set_num the value for trade_statistics_sh.set_num
     *
     * @mbggenerated Tue Dec 12 16:29:18 CST 2017
     */
    public void setSet_num(Integer set_num) {
        this.set_num = set_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_statistics_sh.total
     *
     * @return the value of trade_statistics_sh.total
     *
     * @mbggenerated Tue Dec 12 16:29:18 CST 2017
     */
    public Double getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_statistics_sh.total
     *
     * @param total the value for trade_statistics_sh.total
     *
     * @mbggenerated Tue Dec 12 16:29:18 CST 2017
     */
    public void setTotal(Double total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_statistics_sh.stock
     *
     * @return the value of trade_statistics_sh.stock
     *
     * @mbggenerated Tue Dec 12 16:29:18 CST 2017
     */
    public Double getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_statistics_sh.stock
     *
     * @param stock the value for trade_statistics_sh.stock
     *
     * @mbggenerated Tue Dec 12 16:29:18 CST 2017
     */
    public void setStock(Double stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_statistics_sh.fund
     *
     * @return the value of trade_statistics_sh.fund
     *
     * @mbggenerated Tue Dec 12 16:29:18 CST 2017
     */
    public Double getFund() {
        return fund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_statistics_sh.fund
     *
     * @param fund the value for trade_statistics_sh.fund
     *
     * @mbggenerated Tue Dec 12 16:29:18 CST 2017
     */
    public void setFund(Double fund) {
        this.fund = fund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_statistics_sh.etf
     *
     * @return the value of trade_statistics_sh.etf
     *
     * @mbggenerated Tue Dec 12 16:29:18 CST 2017
     */
    public Double getEtf() {
        return etf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_statistics_sh.etf
     *
     * @param etf the value for trade_statistics_sh.etf
     *
     * @mbggenerated Tue Dec 12 16:29:18 CST 2017
     */
    public void setEtf(Double etf) {
        this.etf = etf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_statistics_sh.national_debt
     *
     * @return the value of trade_statistics_sh.national_debt
     *
     * @mbggenerated Tue Dec 12 16:29:18 CST 2017
     */
    public Double getNational_debt() {
        return national_debt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_statistics_sh.national_debt
     *
     * @param national_debt the value for trade_statistics_sh.national_debt
     *
     * @mbggenerated Tue Dec 12 16:29:18 CST 2017
     */
    public void setNational_debt(Double national_debt) {
        this.national_debt = national_debt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_statistics_sh.government_debt
     *
     * @return the value of trade_statistics_sh.government_debt
     *
     * @mbggenerated Tue Dec 12 16:29:18 CST 2017
     */
    public Double getGovernment_debt() {
        return government_debt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_statistics_sh.government_debt
     *
     * @param government_debt the value for trade_statistics_sh.government_debt
     *
     * @mbggenerated Tue Dec 12 16:29:18 CST 2017
     */
    public void setGovernment_debt(Double government_debt) {
        this.government_debt = government_debt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_statistics_sh.company_debt
     *
     * @return the value of trade_statistics_sh.company_debt
     *
     * @mbggenerated Tue Dec 12 16:29:18 CST 2017
     */
    public Double getCompany_debt() {
        return company_debt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_statistics_sh.company_debt
     *
     * @param company_debt the value for trade_statistics_sh.company_debt
     *
     * @mbggenerated Tue Dec 12 16:29:18 CST 2017
     */
    public void setCompany_debt(Double company_debt) {
        this.company_debt = company_debt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_statistics_sh.convertible_bond
     *
     * @return the value of trade_statistics_sh.convertible_bond
     *
     * @mbggenerated Tue Dec 12 16:29:18 CST 2017
     */
    public Double getConvertible_bond() {
        return convertible_bond;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_statistics_sh.convertible_bond
     *
     * @param convertible_bond the value for trade_statistics_sh.convertible_bond
     *
     * @mbggenerated Tue Dec 12 16:29:18 CST 2017
     */
    public void setConvertible_bond(Double convertible_bond) {
        this.convertible_bond = convertible_bond;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_statistics_sh.bond_repurchase
     *
     * @return the value of trade_statistics_sh.bond_repurchase
     *
     * @mbggenerated Tue Dec 12 16:29:18 CST 2017
     */
    public Double getBond_repurchase() {
        return bond_repurchase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_statistics_sh.bond_repurchase
     *
     * @param bond_repurchase the value for trade_statistics_sh.bond_repurchase
     *
     * @mbggenerated Tue Dec 12 16:29:18 CST 2017
     */
    public void setBond_repurchase(Double bond_repurchase) {
        this.bond_repurchase = bond_repurchase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_statistics_sh.warrant
     *
     * @return the value of trade_statistics_sh.warrant
     *
     * @mbggenerated Tue Dec 12 16:29:18 CST 2017
     */
    public Double getWarrant() {
        return warrant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_statistics_sh.warrant
     *
     * @param warrant the value for trade_statistics_sh.warrant
     *
     * @mbggenerated Tue Dec 12 16:29:18 CST 2017
     */
    public void setWarrant(Double warrant) {
        this.warrant = warrant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_statistics_sh.update_time
     *
     * @return the value of trade_statistics_sh.update_time
     *
     * @mbggenerated Tue Dec 12 16:29:18 CST 2017
     */
    public Date getUpdate_time() {
        return update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_statistics_sh.update_time
     *
     * @param update_time the value for trade_statistics_sh.update_time
     *
     * @mbggenerated Tue Dec 12 16:29:18 CST 2017
     */
    public void setUpdate_time(Date update_time) {
        this.update_time = update_time;
    }
}