package com.ctsec.model.jf;

import java.util.Date;

public class TradeStatisticsSz {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_statistics_sz.month_id
     *
     * @mbggenerated Tue Dec 12 16:29:18 CST 2017
     */
    private Integer month_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_statistics_sz.secu_id
     *
     * @mbggenerated Tue Dec 12 16:29:18 CST 2017
     */
    private Integer secu_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_statistics_sz.name
     *
     * @mbggenerated Tue Dec 12 16:29:18 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_statistics_sz.total
     *
     * @mbggenerated Tue Dec 12 16:29:18 CST 2017
     */
    private Double total;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_statistics_sz.rate
     *
     * @mbggenerated Tue Dec 12 16:29:18 CST 2017
     */
    private Double rate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_statistics_sz.stock
     *
     * @mbggenerated Tue Dec 12 16:29:18 CST 2017
     */
    private Double stock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_statistics_sz.fund
     *
     * @mbggenerated Tue Dec 12 16:29:18 CST 2017
     */
    private Double fund;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_statistics_sz.debt
     *
     * @mbggenerated Tue Dec 12 16:29:18 CST 2017
     */
    private Double debt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_statistics_sz.warrant
     *
     * @mbggenerated Tue Dec 12 16:29:18 CST 2017
     */
    private Double warrant;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_statistics_sz.update_time
     *
     * @mbggenerated Tue Dec 12 16:29:18 CST 2017
     */
    private Date update_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_statistics_sz
     *
     * @mbggenerated Tue Dec 12 16:29:18 CST 2017
     */
    public TradeStatisticsSz(Integer month_id, Integer secu_id, String name, Double total, Double rate, Double stock, Double fund, Double debt, Double warrant, Date update_time) {
        this.month_id = month_id;
        this.secu_id = secu_id;
        this.name = name;
        this.total = total;
        this.rate = rate;
        this.stock = stock;
        this.fund = fund;
        this.debt = debt;
        this.warrant = warrant;
        this.update_time = update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_statistics_sz
     *
     * @mbggenerated Tue Dec 12 16:29:18 CST 2017
     */
    public TradeStatisticsSz() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_statistics_sz.month_id
     *
     * @return the value of trade_statistics_sz.month_id
     *
     * @mbggenerated Tue Dec 12 16:29:18 CST 2017
     */
    public Integer getMonth_id() {
        return month_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_statistics_sz.month_id
     *
     * @param month_id the value for trade_statistics_sz.month_id
     *
     * @mbggenerated Tue Dec 12 16:29:18 CST 2017
     */
    public void setMonth_id(Integer month_id) {
        this.month_id = month_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_statistics_sz.secu_id
     *
     * @return the value of trade_statistics_sz.secu_id
     *
     * @mbggenerated Tue Dec 12 16:29:18 CST 2017
     */
    public Integer getSecu_id() {
        return secu_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_statistics_sz.secu_id
     *
     * @param secu_id the value for trade_statistics_sz.secu_id
     *
     * @mbggenerated Tue Dec 12 16:29:18 CST 2017
     */
    public void setSecu_id(Integer secu_id) {
        this.secu_id = secu_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_statistics_sz.name
     *
     * @return the value of trade_statistics_sz.name
     *
     * @mbggenerated Tue Dec 12 16:29:18 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_statistics_sz.name
     *
     * @param name the value for trade_statistics_sz.name
     *
     * @mbggenerated Tue Dec 12 16:29:18 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_statistics_sz.total
     *
     * @return the value of trade_statistics_sz.total
     *
     * @mbggenerated Tue Dec 12 16:29:18 CST 2017
     */
    public Double getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_statistics_sz.total
     *
     * @param total the value for trade_statistics_sz.total
     *
     * @mbggenerated Tue Dec 12 16:29:18 CST 2017
     */
    public void setTotal(Double total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_statistics_sz.rate
     *
     * @return the value of trade_statistics_sz.rate
     *
     * @mbggenerated Tue Dec 12 16:29:18 CST 2017
     */
    public Double getRate() {
        return rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_statistics_sz.rate
     *
     * @param rate the value for trade_statistics_sz.rate
     *
     * @mbggenerated Tue Dec 12 16:29:18 CST 2017
     */
    public void setRate(Double rate) {
        this.rate = rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_statistics_sz.stock
     *
     * @return the value of trade_statistics_sz.stock
     *
     * @mbggenerated Tue Dec 12 16:29:18 CST 2017
     */
    public Double getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_statistics_sz.stock
     *
     * @param stock the value for trade_statistics_sz.stock
     *
     * @mbggenerated Tue Dec 12 16:29:18 CST 2017
     */
    public void setStock(Double stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_statistics_sz.fund
     *
     * @return the value of trade_statistics_sz.fund
     *
     * @mbggenerated Tue Dec 12 16:29:18 CST 2017
     */
    public Double getFund() {
        return fund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_statistics_sz.fund
     *
     * @param fund the value for trade_statistics_sz.fund
     *
     * @mbggenerated Tue Dec 12 16:29:18 CST 2017
     */
    public void setFund(Double fund) {
        this.fund = fund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_statistics_sz.debt
     *
     * @return the value of trade_statistics_sz.debt
     *
     * @mbggenerated Tue Dec 12 16:29:18 CST 2017
     */
    public Double getDebt() {
        return debt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_statistics_sz.debt
     *
     * @param debt the value for trade_statistics_sz.debt
     *
     * @mbggenerated Tue Dec 12 16:29:18 CST 2017
     */
    public void setDebt(Double debt) {
        this.debt = debt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_statistics_sz.warrant
     *
     * @return the value of trade_statistics_sz.warrant
     *
     * @mbggenerated Tue Dec 12 16:29:18 CST 2017
     */
    public Double getWarrant() {
        return warrant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_statistics_sz.warrant
     *
     * @param warrant the value for trade_statistics_sz.warrant
     *
     * @mbggenerated Tue Dec 12 16:29:18 CST 2017
     */
    public void setWarrant(Double warrant) {
        this.warrant = warrant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_statistics_sz.update_time
     *
     * @return the value of trade_statistics_sz.update_time
     *
     * @mbggenerated Tue Dec 12 16:29:18 CST 2017
     */
    public Date getUpdate_time() {
        return update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_statistics_sz.update_time
     *
     * @param update_time the value for trade_statistics_sz.update_time
     *
     * @mbggenerated Tue Dec 12 16:29:18 CST 2017
     */
    public void setUpdate_time(Date update_time) {
        this.update_time = update_time;
    }
}